### ISSUE TITLE
Generate Invoice from Erpnext

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#102]
In the checkout, add a functionality to generate the invoice. It should create a sales order in ERPNext and then download the invoice

**Comment by meomancer** [comment]
This is already done by PR : https://github.com/kartoza/GeoHosting/pull/153

**Comment by EliVolsch** [comment]
We need to revisit this issue as we currently only generate sales orders and not Tax Invoices.

# GSH Invoicing

We need to provide invoices for customers based on the currency selected and payment portal used. Users buying products with Paystack or Kartoza (South Africa) should receive an invoice generated from ERPNext in Rand value. However users paying with Stripe or Kartoza Lda(Portugal) needs to receive an invoice from ERPNext and additionally to comply with EU regulations a government issued invoice. Below is a detailed description of the information required to generate the invoices.

## Invoice Requirements
### South Africa (Rand / Paystack Payments):
Invoices generated for Rand payment require a few key requirements to be a valid tax-invoice.

1) **Vendor Information (This is Kartoza's information)**
   - Company Name 
   - Physical Address
   - Vat Registration Number
2) **Invoice Information**
   - Unique Invoice Number
   - Invoice Issue Date
   - The words "Tax Invoice" clearly displayed
3) **Customer Information**
   - Customer's Name / Company Name
   - Customer's Physical address
   - Customer's VAT number (<span style="color: red;">Compulsory for companies</span>)
4) **Description of Goods / Services**
   - For each line item:
     - Clear Description of Goods / Services
     - Quantity or unit (eg. hours, units)
     - Unit Price (Excluding vat)
     - Line item total (Excluding vat)
5) **Total and VAT Calculation**
   - Subtotal (Sum of all items excluding vat)
   - VAT amount charged (This is 15%)
   - Total amount payable (Including vat)

As an example of an accurate South African Tax Invoice see the fictional document below generated by ERPNext. 

[South Africa Invoice Example](https://kartoza-staging-v14.frappe.cloud/app/print/Sales%20Invoice/ACC-SINV-2025-00001)

## Portugal (Other Currencies / Stripe Payments):
Invoices generated for other currencies will be routed through Kartoza Portugal and would need the following key requirements to be valid:

> **Note**: The invoicing needs to comply with with Portugal's invoicing requirements under **[the Portuguese VAT Code and EU Directive 2006/112/EC](https://taxation-customs.ec.europa.eu/document/download/16cea95c-1821-4f43-98c3-26b32e867d73_fr)** and [Portugal's VAT Rules](https://vat-one-stop-shop.ec.europa.eu/national-vat-rules/portugal-vat-rules_en). Also Reference [Portugal's VAT CODE](https://www2.gov.pt/en-GB/cidadaos-europeus-viajar-viver-e-fazer-negocios-em-portugal/impostos-para-atividades-economicas-em-portugal/imposto-sobre-valor-acrescentado-iva-em-portugal)

1) **Supplier Information (Kartoza Portugal Information)**
   - Company name
   - Registered business address
   - Portuguese VAT number (NIF – Número de Identificação Fiscal) – format: `PTXXXXXXXXX`
   - Company registration number (from Conservatória do Registo Comercial)
   - Contact details (email, phone – optional but recommended)
2) **Invoice Header**
   - The word "Fatura" (Invoice) or "Fatura Simplificada" (Simplified Invoice – for smaller amounts)
   - Unique and sequential invoice number
   - Date of issue (DD/MM/YYYY format)
3) **Customer Information**
   - Name (or company name)
   - Address (for B2B or cross-border)
   - VAT number (if B2B within the EU or outside Portugal)
   - For intra-EU B2B, the customer's VAT number must be validated via VIES: [https://ec.europa.eu/taxation_customs/vies/](https://ec.europa.eu/taxation_customs/vies/)
4) **Line Item Details**
   - For each product or service:
     - Description
     - Quantity
     - Unit price excluding VAT
     - Total amount excluding VAT
5) **VAT and Totals**
    - VAT rate per item (usually 23%, but can be 6% or 13% depending on the product/service)
    - Total VAT amount
    - Total amount including VAT
    - If VAT is not charged (e.g., reverse charge, export, exempt), a legal justification must be included (see next section)


## Information to be collected

In order to satisfy the above mentioned [Invoice Requirements](#invoice-requirements) we need to collect the following information from our clients, before a invoice is issued. 

|       Item      |              Personal              |               Company              |
|:---------------|:----------------------------------|:----------------------------------|
| Name            |              Full name             |       Registered Company Name      |
| Billing Address | Street, City, Postal Code, Country | Street, City, Postal Code, Country |
| VAT/TAX Number  |              Optional              |             Compulsory             |
| Contact Details |                Email               |                Email               |


### Workflow for Collecting Information:
Collecting the information would then in turn have an effect on the workflow, as some of the items need to be present before an invoice can be issued to a client. The below diagram suggest flow changes to be implemented.

```mermaid
flowchart TD
    A["Customer navigates to platform - anonymous user"] --> B["View product"]
    B --> C["Select product"]
    C --> D["Select product tier"]
    D --> E{"Is user logged in?"}
    E -- No --> F["Register"]
    F --> G["Go to configuration page"]
    E -- Yes --> G
    G --> H["Select personal or company"]
    H --> I{"Personal or Company?"}
    I -- Personal --> J{"Is billing address complete?"}
    J -- No --> K["Show billing modal and save to profile"]
    J -- Yes --> L["Load billing from profile"]
    I -- Company --> M{"Company details exist?"}
    M -- No --> N["Open modal to create company"]
    M -- Yes --> O["Load company details"]
    K --> Q["Click Next"]
    L --> Q
    N --> Q
    O --> Q
    Q --> S["Pay with Paystack or Stripe"]
    S --> T{"Was payment successful?"}
    T -- No --> U["Show payment failed message"]
    U --> S
    T -- Yes --> TT["Using send information to ERPNext Via API"]
    TT --> TTT["ERP Next Generates, sales order, then converts to invoice"]
    TTT --ERP Generated--> X["Show invoice download"]
    TTT --If Kartoza Portugal Client--> AA["Generate Portugal invoice, manually or via API if needed"]
    X --> Y["Save to dashboard"]
    AA --> Y
```

### ERP: 

Our current ERPNext workflow stops short of generating the invoice, and only generates a sales order. This process needs to be expanded so a Tax invoice is generated for the purchase.

Some functions can be done using ERPNext, like the VAT/TAX calculation. On ERP if the tax has been set for the company we can tick ''Vat Included in item price" which will automatically calculate the vat in the subtotal, with out changing the item price.

### API for Portugal Invoicing

It seem there are some online API tool which can be used to automatically generate a government invoice for Portugal given that it is supplied with the required information. This can be used to automate the process and keep the company compliant with EU regulations.

This generated invoice should then be made available for the client to download alongside the ERP generated invoice. Below is a list of API's that I have found:

| Name                               | API                                                  | Free Plan            | Starting Price       | Notes                                                                          |
| ---------------------------------- | ---------------------------------------------------- | -------------------- | -------------------- | ------------------------------------------------------------------------------ |
| **Moloni**                         | ✅ [API Docs](https://www.moloni.pt/dev/)             | ❌                    | €4.50/month          | One of the most developer-friendly; supports recurring billing, multi-company. |
| **InvoiceXpress**                  | ✅ [API Docs](https://invoicexpress.com/api)          | ✅ (5 invoices/month) | €10/month (Lite)     | Very clean UI, easy to integrate. Free tier available for testing/dev.         |
| **PHC GO**                         | ✅ [API Docs](https://phcgo.net/)                     | ❌                    | €9/month             | Enterprise-focused. Slightly more complex.                                     |
| **Jasmin Software (by PRIMAVERA)** | ✅ [API Docs](https://developers.jasminsoftware.com/) | ✅ (limited)          | €10.99/month         | Offers excellent support for digital businesses. Modern UI.                    |
| **TIC Online**                     | ✅ [API Docs](https://www.ticonline.pt/)              | ❌                    | From €7.50/month     | Simpler option, used by many small Portuguese companies.                       |


## Tasks

- [ ] Implement a workflow that can collect all the required information form client before generating invoice.
- [ ] Implement workflow checks for mandatory information.
- [ ] Check ERPNext invoice process, to generate Tax Invoice
- [ ] Investigate and discuss Portugal Government Tax Invoice process and possible implementation of an API.

**Comment by EliVolsch** [comment]
## Update on GSH Invoicing Workflow for International Payments

We recently held a meeting with Marcelle and Lin-Mari to discuss the GSH invoicing process for non–South African payments. During the discussion, we identified several potential issues related to having invoices generated directly by the platform. These issues may carry legal implications for the company as a whole.

As a result, we have agreed that the most appropriate way forward is to follow the workflows below:

### 1. South African Payments

The current workflow for South African payments is generally correct. However, we need to ensure that a valid **tax invoice** is generated and issued to the client.

For reference, this is what the invoice should look like once generated: [Example SA Tax Invoice](https://kartoza-staging-v14.frappe.cloud/app/print/Sales%20Invoice/ACC-SINV-2025-00001).
 
The wording on the invoice must also be updated:
  - **Remove**: “Payment Due Date”
  - **Replace with**: “Payment Status: Paid”
  - **Remove**: "VAT Number"
  - **Replace with**: "Tax Number"

### 2. Portugal/International Payments

To comply with Portuguese regulations and internal workflows, we propose the following steps:

1. **Once payment is completed**:
   - ERPNext should generate a **Sales Order** (visible in GSH).
   - ERPNext should also generate a **Tax Invoice** (not visible to the client).
2. **The tax invoice** must be **emailed** to the following recipients:
   - Marcelle  
   - Lin-Mari  
   - Ana Paula
3. **Ana Paula** will then **manually generate** the official invoice on the **FE-AP portal**, which will automatically be shared with the client through that system.

Workflow diagram updates:
Givne the suggested changes the workflow diagram is more likely to represent the following:

<img width="589" height="741" alt="Image" src="https://github.com/user-attachments/assets/7901b5b9-baf2-4eb7-b2ca-64524fe9f041" />

### Automating Processes:
Unfortunately, at this stage, there is not enough volume to justify automating this process further or implementing the API. Additionally, the FE-AP invoice cannot be displayed on the GSH platform, as it is a private document only visible to the issuer and the recipient.

## Additional Items:
- During the meeting it was mentioned that regular Stripe report would be required as proof of transactions for Kartoza LDA, and we would need to configure this or include Ana Paula as a recipient on stripe.   
- It was also mentioned that we are required to complete a [W-8 BEN-E](https://stripe.com/resources/more/w-8-ben-tax-form) form in order to be compliant with USA tax regulations.

### **Updated Tasks List**:
- [ ] Update checkout workflow to generate invoices from ERPNext.
- [ ] Update invoice wording to replace "Payment Due Date" with "Payment Status: Paid" and "VAT Number" with "TAX Number".
- [ ] Purchases made using stripe should forward the invoice to the following team: Lin-Mari, Ana Paula, Marcelle Sutton to be able to manually generate FE-AP invoices.
- [ ] Ensure the checkout procedure captures all required client details for invoicing purposes

### Additional items:
- [ ] Double check that Kartoza LDA information is correctly setup on Stripe.
- [ ] Investigate generate regular reports for Stripe, as they will be required for Kartoza LDA tax purposes.
- [ ] Ensure we have completed a [W-8 BEN-E](https://stripe.com/resources/more/w-8-ben-tax-form) form (Required for US tax regulations). 
- [ ] Confirm and configure the TAX percentage

**Comment by meomancer** [comment]
1. For south africa, we send user the sales invoice
2. For LDA, we send user the sales order invoice
3. For both, we still need to generate sales invoice

**Comment by meomancer** [comment]
Hi @EliVolsch 
Is this done? If yes, could we close this ticket?
